### PR TITLE
Could you please explain why it only works with these changes?

### PR DESCRIPTION
**Pull request by sergmoro1**
After installation swears on two things: not right sourcePath and an invalid character in arrays definition (js, css).

### CODE REVIEW

**Comment by SilverFire** [comment]
> and an invalid character in arrays definition (js, css).

Probably your PHP version is too old. Conditions in property definition were added in 5.5 or 5.6, don't remember exactly

> not right sourcePath

Show me the output of these lines:

```php
foreach([
    '@bower',
    '@npm',
    '@vendor',
] as $alias) {
    echo $alias . ': ' . Yii::getAlias($alias, false) . "<br />";
}
```

**Comment by sergmoro1** [comment]
Morning, thanks for your reply!
PHP version:
I see.

Aliases:
@bower: /home/sm1/www/vorst/vendor/bower
@npm: /home/sm1/www/vorst/vendor/npm
@vendor: /home/sm1/www/vorst/vendor

**Comment by SilverFire** [comment]
You should override aliases in your application config:

```php
  $config = [
        ...
        'aliases' => [
            '@bower' => '@vendor/bower-asset',
            '@npm'   => '@vendor/npm-asset',
        ],
        ...
    ];
```

**Comment by sergmoro1** [comment]
Thanks. It can be changed in config and it's ease. But what about? 
YII_DEBUG ? 'js/select2.full.js' : 'js/select2.full.min.js',
and
YII_DEBUG ? 'css/select2.css' : 'css/select2.min.css',
Is it so necessary to use a code that cannot be used on the server? 

PHP 5.6.33-3+ubuntu14.04.1+deb.sury.org+1 (cli) 

With your require section:

 "require": {
        "php": ">5.6",
        "yiisoft/yii2": "*",
        "bower-asset/select2": "^4.0.3"
},

**Comment by SilverFire** [comment]
> Is it so necessary to use a code that cannot be used on the server?

I did not get this point. Why it can not be used on server?

**Comment by sergmoro1** [comment]
Error on "?".

**Comment by SilverFire** [comment]
PHP 5.6 supports this syntax construction for sure: https://3v4l.org/5YaGE

**Comment by sergmoro1** [comment]
Yes, it worked! There was version PHP 5.5, I updated it to 5.6, but the error message remained. Now check again and it work properly. Thank you very much for your patience!

**Comment by SilverFire** [comment]
You're welcome

**Pull request closed without merging**
